name: CodeQL Analysis on Push

on:
 push:
    branches:
      - main

jobs:
 build-and-analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: msbuild TestCasesCurated.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
